export const environment = {
  production: false,
  apiKey:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NGU5YmQyMC0zZWQ1LTQ1MzMtYTdlZi1iMWYwOWJhNjVkMzgiLCJlbWFpbCI6InRpYWdvQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJUaWFnbyBTYW50aW5pIiwibmJmIjoxNjk2Mjc0MjI0LCJleHAiOjE2OTYzMDMwMjQsImlhdCI6MTY5NjI3NDIyNCwiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.Zd72-9oGPNUb0yaIKtZFmEXIFXT1kGPxHsL_9Xeu-6c',
};
